### ISSUE TITLE
Feature request: Add promises support.

### ISSUE THREAD

**Issue by ilyaglebov** [wdavidw/node-csv#211]
Please consider adding promises support. Latest versions of node.js have almost full es6 features coverage and it would be very convenient to use functions with `yield` keyword, for example:

``` javascript
// Current (callback-based) approach:
csvExporter.stringify(deposits, { delimiter: ',' }, (err, out) => {
  // some logic here
})

// Promises + generators approach:
let out;
try {
  out = yield csvExporter.stringify(deposits, { delimiter: ',' });
} catch (err) {
  throw new Error(err);
}
```

Thanks!

**Comment by wdavidw** [comment]
There is one problem with the API. The promise API as you suggest it is in conflit with the current one because it already return something, an instance of stream.Transform, just like with sync, we could create a new module called promise inside the parser and stringifier project which will provide an alernative API

**Comment by polidore** [comment]
+1

**Comment by leonardodelfino** [comment]
+1

**Comment by kachkaev** [comment]
Maybe there could be a wrapper package similar to [fs-promise](https://www.npmjs.com/package/fs-promise) that would wrap callback functionality into promises? async/await code style will become mainstream pretty soon.

**Comment by kachkaev** [comment]
[node-csv-promise](https://www.npmjs.com/package/node-csv-promise) package name is free

**Comment by kachkaev** [comment]
That module might be be as easy as something like this:

```
const promisify = require('es6-promisify');
const originalStringify = require('csv-stringify');
module.exports.stringify = promisify(originalStringify);

// ... promisify other methods in a similar way
```

**Comment by wdavidw** [comment]
There is no need, we just need to create a module in csv-parse similar to [sync](https://github.com/wdavidw/node-csv-parse/blob/master/src/sync.coffee.md).

Now, let's keep in mind this is totally useless. Using promise means no streaming which mean no scallability since u'll have have to keep the csv in memory which mean synchronous code wich make using a promise a non sense.

**Comment by kachkaev** [comment]
@wdavidw what do you think of moving the existing node-csv repos into a new org, let's say https://github.com/node-csv? The promisified versions of the modules could be hosted there as well, but maintained by a wider community of contributors, so that there is less pressure on you. I've been seeing a few projects moving to dedicated groups recently to ease their maintenance. An example on top of my head is http://mxstbr.blog/2017/01/the-future-of-react-boilerplate/ Groups seem like a good option for keeping multiple closely-related repos nicely bundled together.

**Comment by kachkaev** [comment]
It's true that promises are less efficient than streams, however this is OK in many cases.  Not all CSVs are 10s of megs in size :-)

**Comment by wdavidw** [comment]
You can interrupt a promise chain but how can u interrupt an internal execution (same tick) ?

**Comment by kachkaev** [comment]
I guess so. If the internal implementation of the method uses a stream or some other implementation that spreads the task between the multiple ticks, then yes, why not? After all, a promise is just a pair of async callbacks (one for success, another for failure).

**Comment by kachkaev** [comment]
By interrupting the execution I simply meant spreading it between multiple ticks. The main thread wont' be blocked as it happens with the sync mode.

**Comment by wdavidw** [comment]
then it wont be the case here, the code will be blocking just like sync, this is why I still dont see the point using a promise when you could have `csv = parse(data)`. Look at the sync module, duplicate it, name it "promise.coffee", wrap it around a Promise, write a test and finnally i will merge: )

**Comment by kachkaev** [comment]
The problem with sync option now is that it only exists for `parse` as far as I understand. Wanted to use `stringify` synchronously and had to promisify it :-) Found this thread then.

**Comment by wdavidw** [comment]
you're right, but that would be a good start

**Comment by sent1nel** [comment]
A benefit of async/await is being able to use promise-returning functions more algebraically.

Consider:

```
let thing;
csv.stringify(transformObjectIntoThing(object), (err, data) => { thing = data; })`
```
vs
```
let thing = await csv.stringify(transformObjectIntoThing(object));
```

**Comment by wdavidw** [comment]
still the same reasoning, why using async/await when it using sync mode would work just the same, it does make any sense. If you dont need streaming, then go sync mode. I should clarify the doc, sync mode is calling any blocking IO, it is just buffering all in memory.

**Comment by sent1nel** [comment]
I'm not a zealot, I personally ended up just using async mode with streams.

**Comment by wdavidw** [comment]
Don't know what zealot means, but i wasnt offending you. Taking you're sample:

```js
let row;
csv.stringify(data, (err, data) => { row = data; });
```

You could rewrite it as:

```
stringify = require('csv-stringify/lib/sync')
row = stringify(data);
```

And it would be exactly the same behavior/memory consumption/speed/implementation as:

```
let row = await csv.stringify(data);
```

Thus my comment on why using promise-style code when it doesnt provide anything more than its bare metal javascript counterpart.

Now, that made me realise, we are not exposing "sync" modules from "csv-parse and "csv-stringify" in the "csv" module, that is a mistake (and a different issue).

**Comment by wdavidw** [comment]
There is only one valid use case to this module: when the input is a stream reader and the output is not a stream writer.  In such case, the overall dataset is stored in memory. The code is no longer scalable. I would rather encourage the user to use the sync module present in the package because it makes the user aware of this situation by passing a CSV string and getting a JavaScript array. Unless used carefully, this could be considered an antipattern. This is why I am not eager at implementing this feature. Now, since people are implemented this feature externally, I question the fact that we should integrate it and well document its limitation in the official website.

**Comment by benjaminpjones** [comment]
I think the reason that so many people ask about a Promises API is that the callback API is so prominently documented without use of streams.  It is easy to believe this example (provided on the npm page):

```
const input = [ [ '1', '2', '3', '4' ], [ 'a', 'b', 'c', 'd' ] ]
stringify(input, function(err, output) {
  const expected = '1,2,3,4\na,b,c,d\n'
  assert.strictEqual(output, expected, `output.should.eql ${expected}`)
  console.log("Passed.", output)
})
```

can be changed to:

```
const input = [ [ '1', '2', '3', '4' ], [ 'a', 'b', 'c', 'd' ] ]
stringify(input).then(function(output) {
  const expected = '1,2,3,4\na,b,c,d\n'
  assert.strictEqual(output, expected, `output.should.eql ${expected}`)
  console.log("Passed.", output)
})
```

Perhaps the solution is to make it clear in the headlining documentation that processing all data at once is a synchronous operation, and therefore the sync API should be used in this very simple case:

```
const stringify = require('csv-stringify/sync')

const input = [ [ '1', '2', '3', '4' ], [ 'a', 'b', 'c', 'd' ] ]
const output = stringify(input)
const expected = '1,2,3,4\na,b,c,d\n'
assert.strictEqual(output, expected, `output.should.eql ${expected}`)
console.log("Passed.", output)
```

**Comment by wdavidw** [comment]
I agree, there has been some initiative in the past to clarify this recommendation but it is probably not enough.

**Comment by ajmas** [comment]
Old issue, but maybe clarify the Promise stance in the docs and maybe provide a suitable example,

This is what I have in my code:

```ts
      const csvData = await new Promise((resolve, reject) => {
        csvStringify(
          unassignedPeople as Input,
          {
            header: true,
            columns
          } as Options,
          (error: Error, records: string) => {
            if (error) {
              reject(error);
              return;
            }
            resolve(records);
          }
        );
      });
```

**Comment by wdavidw** [comment]
Promise just doesn't make any sense. It is complicated in a documentation to explain users to not use a useless API. Said differently, I am all in to improve the doc into explaining what to do, but reluctant to incorporate instructions explaining what to not do.

**Comment by ajmas** [comment]
Fair enough.

I suppose in this scenario the appropriate example would demonstrate how to make a string the output of the csv, rather than a file. Also, in a way that ensures the flow of the calling function doesn’t continue until the string has been generated.

**Comment by wdavidw** [comment]
I spited the API documentation into multiple section, just like how parse is organized. I might introduce a promise API at some point. It isn't worse than the callback one, and be clear about when to use it.
